package cli

import (
	"path/filepath"
	"strings"
	"testing"

	"github.com/ozgurcd/achta/internal/buildinfo"
)

// RULE: WIKI-DERIVE-HEADER-VERSION-1
func TestWikiCheckHeaderVersionOnly(t *testing.T) {
	root, _ := freshPinStaleDerive(t)
	page := filepath.Join(root, "wiki/repos/sample.md")
	wikiBehaviorRun(t, root, 0, "wiki", "derive", "--write")
	fresh := readTestFile(t, page)
	old := strings.Replace(fresh, "Generated by achta "+buildinfo.Version+" ", "Generated by achta v0.0.1 ", 1)
	if old == fresh {
		t.Fatal("fixture did not change the generator version")
	}
	for _, newline := range []string{"\n", "\r\n"} {
		t.Run(strings.ReplaceAll(newline, "\n", "LF"), func(t *testing.T) {
			input := strings.ReplaceAll(old, "\n", newline)
			writeTestFile(t, page, input)
			for _, mode := range [][]string{{"wiki", "check"}, {"wiki", "check", "--only", "derive", "--json"}} {
				out := wikiBehaviorRun(t, root, 0, mode...)
				if !strings.Contains(out, "generator version drift") || !strings.Contains(out, "v0.0.1") || !strings.Contains(out, buildinfo.Version) {
					t.Fatalf("missing version drift note: %s", out)
				}
				if readTestFile(t, page) != input {
					t.Fatal("wiki check wrote the page")
				}
			}
			wikiBehaviorRun(t, root, 1, "wiki", "derive", "--check")
			wikiBehaviorRun(t, root, 0, "wiki", "derive", "--write")
			if readTestFile(t, page) != strings.ReplaceAll(fresh, "\n", newline) {
				t.Fatal("derive writer did not restore the running version")
			}
		})
	}
	for name, input := range map[string]string{
		"fact":            strings.Replace(old, "| Repo HEAD |", "| Wrong HEAD |", 1),
		"header wording":  strings.Replace(old, "do not edit", "please edit", 1),
		"invalid version": strings.Replace(old, "v0.0.1", "unknown", 1),
		"spacing":         strings.Replace(old, "v0.0.1 ", "v0.0.1  ", 1),
	} {
		t.Run(name, func(t *testing.T) {
			writeTestFile(t, page, input)
			out := wikiBehaviorRun(t, root, 1, "wiki", "check", "--only", "derive", "--json")
			if !strings.Contains(out, `"status":"fail"`) || strings.Contains(out, "generator version drift") {
				t.Fatalf("non-version drift was accepted: %s", out)
			}
			if readTestFile(t, page) != input {
				t.Fatal("failed check wrote the page")
			}
		})
	}
}
