package cli

import (
	"bytes"
	"encoding/json"
	"path/filepath"
	"strings"
	"testing"

	"github.com/ozgurcd/achta/internal/buildinfo"
)

func wikiBehaviorRun(t *testing.T, root string, want int, args ...string) string {
	t.Helper()
	var out, errout bytes.Buffer
	code := Run(append([]string{"--wiki-dir", filepath.Join(root, "wiki")}, args...), &out, &errout, buildinfo.Version)
	if code != want {
		t.Fatalf("%v: exit=%d want=%d output=%s stderr=%s", args, code, want, out.String(), errout.String())
	}
	return out.String()
}

func TestWikiBehaviorScope(t *testing.T) {
	root, _ := freshPinStaleDerive(t)
	writeTestFile(t, filepath.Join(root, "wiki/repos/broken.md"), "not valid frontmatter\n")
	out := wikiBehaviorRun(t, root, 0, "wiki", "check", "--only", "freshness", "--repo", "sample", "--json")
	if !strings.Contains(out, `"status":"not_judged"`) || !strings.Contains(out, "broken") || !strings.Contains(out, "not selected by --repo") {
		t.Fatalf("missing explicit exclusion: %s", out)
	}
	out = wikiBehaviorRun(t, root, 1, "wiki", "check", "--exclude", "broken=pin unchanged", "--json")
	if !strings.Contains(out, "pin unchanged") || !strings.Contains(out, `"name":"derive","status":"fail"`) {
		t.Fatalf("scope suppressed another judgement: %s", out)
	}
	out = wikiBehaviorRun(t, root, 0, "wiki", "check", "--exclude", "broken=pin unchanged", "--exclude", "sample=pin unchanged")
	if !strings.Contains(out, "NOT judged") || !strings.Contains(out, "sample") || !strings.Contains(out, "broken") {
		t.Fatalf("human exclusion missing: %s", out)
	}
	for _, args := range [][]string{{"--repo", "absent"}, {"--exclude", "sample"}, {"--exclude", "sample="}, {"--repo", "sample", "--exclude", "sample=conflict"}, {"--repo", "sample", "--repo", "sample"}} {
		wikiBehaviorRun(t, root, 2, append([]string{"wiki", "check", "--json"}, args...)...)
	}
	t.Log("PASS selected freshness; NOT judged broken with reason; derive still fails; malformed scopes exit 2")
}

func TestWikiBehaviorFreshnessEnforces(t *testing.T) {
	root, repo := freshPinStaleDerive(t)
	runGit(t, repo, "commit", "-am", "advance")
	out := wikiBehaviorRun(t, root, 1, "wiki", "freshness", "--repo", "sample", "--json")
	if !strings.Contains(out, `"mode":"enforcing"`) || !strings.Contains(out, `"status":"behind"`) {
		t.Fatalf("missing enforced drift: %s", out)
	}
	out = wikiBehaviorRun(t, root, 0, "wiki", "freshness", "--repo", "sample", "--report-only", "--json")
	if !strings.Contains(out, `"mode":"report_only"`) || !strings.Contains(out, `"status":"drift"`) {
		t.Fatalf("report mode hid drift: %s", out)
	}
	wikiBehaviorRun(t, root, 1, "wiki", "freshness", "--repo", "sample", "--strict")
	t.Log("PASS behind page: default exit 1; report_only exit 0 with drift retained")
}

func TestWikiBehaviorDerivePreviewAndHeader(t *testing.T) {
	root, _ := freshPinStaleDerive(t)
	page := filepath.Join(root, "wiki/repos/sample.md")
	before := readTestFile(t, page)
	for _, args := range [][]string{{"wiki", "derive", "--check", "--json"}, {"wiki", "derive", "--json"}} {
		out := wikiBehaviorRun(t, root, 1, args...)
		if readTestFile(t, page) != before {
			t.Fatal("read-only derive changed bytes")
		}
		if !strings.Contains(out, `"before":`) || !strings.Contains(out, `"after":`) || !strings.Contains(out, "Generated by achta "+buildinfo.Version) || strings.Contains(out, "wiki/tools/wiki-derive.sh") {
			t.Fatalf("missing honest preview/header: %s", out)
		}
	}
	out := wikiBehaviorRun(t, root, 0, "wiki", "derive", "--write", "--json")
	if !strings.Contains(out, `"status":"updated"`) || !strings.Contains(out, "wiki/repos/sample.md") {
		t.Fatalf("write not named: %s", out)
	}
	if readTestFile(t, page) == before {
		t.Fatal("explicit derive did not write")
	}
	wikiBehaviorRun(t, root, 0, "wiki", "derive", "--check")
	t.Log("PASS preview changes no byte; header names Achta version; --write names updated page")
}

func TestWikiBehaviorPinOnlyMetadata(t *testing.T) {
	root, _, head := testWorkspaceRepo(t, "sample")
	page := filepath.Join(root, "wiki/repos/sample.md")
	original := strings.ReplaceAll(pageFixtureCLI, "REPOSITORY", "sample")
	original = strings.Replace(original, "# sample\n", "# sample\n\nLead at aaaaaaa on 2026-09-01: old slice.\n", 1)
	for _, newline := range []string{"\n", "\r\n"} {
		before := strings.ReplaceAll(original, "\n", newline)
		writeTestFile(t, page, before)
		out := wikiBehaviorRun(t, root, 0, "wiki", "pin", "sample", "--sha", head, "--verified", "2026-09-17", "--attest-reviewed", "--json")
		want := strings.Replace(before, "verified_against: sample @ aaaaaaa", "verified_against: sample @ "+head, 1)
		want = strings.Replace(want, "verified: 2026-09-01", "verified: 2026-09-17", 1)
		want = strings.Replace(want, "updated: 2026-09-01", "updated: 2026-09-17", 1)
		if got := readTestFile(t, page); got != want {
			t.Fatalf("pin changed more or less than pin/dates:\n%s", got)
		}
		if !strings.Contains(out, "PM") || !strings.Contains(out, "front lead") {
			t.Fatalf("missing ownership notice: %s", out)
		}
	}
	t.Log("PASS pin and both dates advance; DERIVED and lead bytes identical (LF and CRLF)")
}

func TestWikiBehaviorRecipeOrder(t *testing.T) {
	root, _, _ := testWorkspaceRepo(t, "sample")
	writeTestFile(t, filepath.Join(root, "expected.txt"), "first\nsecond\nthird\nfourth\n")
	writeTestFile(t, filepath.Join(root, "Makefile"), "check:\n\tsecond\n\tfirst\n\tthird\n\tfourth\n")
	args := []string{"recipe", "check", "--makefile", "Makefile", "--target", "check", "--expect-file", "expected.txt", "--expect-order", "--json"}
	out := wikiBehaviorRun(t, root, 1, args...)
	if !strings.Contains(out, "expected-order") {
		t.Fatalf("order mismatch not named: %s", out)
	}
	writeTestFile(t, filepath.Join(root, "Makefile"), "check:\n\tfirst\n\tsecond\n\tthird\n\tfourth\n")
	wikiBehaviorRun(t, root, 0, args...)
	t.Log("PASS identical membership reordered exit 1; original order exit 0")
}

func TestWikiBehaviorExplicitWikiWrites(t *testing.T) {
	selected, _, head := testWorkspaceRepo(t, "sample")
	other, _, _ := testWorkspaceRepo(t, "sample")
	page := strings.ReplaceAll(pageFixtureCLI, "REPOSITORY", "sample")
	for _, root := range []string{selected, other} {
		writeTestFile(t, filepath.Join(root, "wiki/repos/sample.md"), page)
	}
	t.Chdir(other)
	wikiBehaviorRun(t, selected, 0, "wiki", "pin", "sample", "--sha", head, "--verified", "2026-09-17", "--attest-reviewed")
	// Use the existing --check API before any changes to prove selected reads too.
	wikiBehaviorRun(t, selected, 1, "wiki", "derive", "--check")
	wikiBehaviorRun(t, selected, 0, "wiki", "derive", "--write")
	if readTestFile(t, filepath.Join(other, "wiki/repos/sample.md")) != page {
		t.Fatal("pin or preview wrote to ambient wiki")
	}
	if !strings.Contains(readTestFile(t, filepath.Join(selected, "wiki/repos/sample.md")), head) {
		t.Fatal("selected wiki was not pinned")
	}
	register := "# Decisions\n\n## Platform\n\n### P-001 — first choice\nExisting body.\n\n## UI\n"
	for _, root := range []string{selected, other} {
		writeTestFile(t, filepath.Join(root, "wiki/platform/decisions.md"), register)
	}
	writeTestFile(t, filepath.Join(selected, "body.txt"), "Measured choice.\n")
	wikiBehaviorRun(t, selected, 0, "decision", "add", "--title", "Selection", "--body-file", "body.txt")
	if readTestFile(t, filepath.Join(other, "wiki/platform/decisions.md")) != register {
		t.Fatal("decision wrote to ambient wiki")
	}
	if !strings.Contains(readTestFile(t, filepath.Join(selected, "wiki/platform/decisions.md")), "P-002 — Selection") {
		t.Fatal("decision ignored selected wiki")
	}
	t.Log("PASS --wiki-dir pin and decision writes and derive reads select the requested wiki from another workspace")
}

func TestWikiBehaviorFailureAndHelp(t *testing.T) {
	root, _ := freshPinStaleDerive(t)
	writeTestFile(t, filepath.Join(root, "wiki/repos/broken.md"), "broken\n")
	out := wikiBehaviorRun(t, root, 2, "wiki", "freshness", "--report-only", "--json")
	if !strings.Contains(out, `"mode":"report_only"`) || !strings.Contains(out, `"status":"cannot_evaluate"`) {
		t.Fatalf("report hid unavailable evidence: %s", out)
	}
	// Unknown global flags cannot be used to change the authoritative workspace.
	wikiBehaviorRun(t, root, 2, "wiki", "derive", "--write", "--check", "--json")
	wikiBehaviorRun(t, root, 2, "wiki", "freshness", "--strict=false", "--json")
	// A selected failure must not erase the scope report.
	out = wikiBehaviorRun(t, root, 2, "wiki", "check", "--exclude", "sample=pin unchanged", "--json")
	if !strings.Contains(out, `"not_judged":{"sample":"pin unchanged"}`) {
		t.Fatalf("failure hid exclusions: %s", out)
	}
	for _, pair := range []struct{ family, command, flag string }{{"wiki", "check", "--exclude"}, {"wiki", "freshness", "--report-only"}, {"wiki", "derive", "--write"}, {"wiki", "pin", "front lead"}, {"recipe", "check", "--expect-order"}} {
		var stdout, stderr bytes.Buffer
		if code := Run([]string{pair.family, pair.command, "--help"}, &stdout, &stderr, buildinfo.Version); code != 0 || !strings.Contains(stdout.String(), pair.flag) {
			t.Fatalf("help %s %s: code=%d %s %s", pair.family, pair.command, code, stdout.String(), stderr.String())
		}
	}
}

func TestWikiBehaviorPreviewBytesAndRecipeMultiplicity(t *testing.T) {
	root, _ := freshPinStaleDerive(t)
	page := filepath.Join(root, "wiki/repos/sample.md")
	before := readTestFile(t, page)
	var doc struct {
		Pages []struct{ Before, After string }
	}
	out := wikiBehaviorRun(t, root, 1, "wiki", "derive", "--check", "--json")
	if err := json.Unmarshal([]byte(out), &doc); err != nil || len(doc.Pages) != 1 {
		t.Fatalf("bad preview: %v %s", err, out)
	}
	if doc.Pages[0].Before != before {
		t.Fatal("preview before does not match actual bytes")
	}
	wikiBehaviorRun(t, root, 0, "wiki", "derive", "--write")
	if doc.Pages[0].After != readTestFile(t, page) {
		t.Fatal("preview after does not match written bytes")
	}
	writeTestFile(t, filepath.Join(root, "Makefile"), "check:\n\tfirst\n")
	wikiBehaviorRun(t, root, 1, "recipe", "check", "--makefile", "Makefile", "--target", "check", "--expect-line", "first", "--expect-line", "first", "--expect-order")
	wikiBehaviorRun(t, root, 2, "recipe", "check", "--makefile", "Makefile", "--target", "check", "--expect-order")
}
