package wiki

import (
	"bytes"
	"path/filepath"
	"strings"
	"testing"
)

func TestDeriveCheckThenWrite(t *testing.T) {
	root := t.TempDir()
	repo := filepath.Join(root, "sample")
	mustMkdir(t, filepath.Join(root, "wiki", "repos"))
	mustMkdir(t, repo)
	runGitStatusTest(t, repo, "init", "-b", "main")
	runGitStatusTest(t, repo, "config", "user.name", "Achta Test")
	runGitStatusTest(t, repo, "config", "user.email", "achta@example.invalid")
	mustWrite(t, filepath.Join(repo, "go.mod"), "module example.test/sample\n\ngo 1.27.1\n")
	runGitStatusTest(t, repo, "add", "go.mod")
	runGitStatusTest(t, repo, "commit", "-m", "base")
	pagePath := filepath.Join(root, "wiki", "repos", "sample.md")
	mustWrite(t, pagePath, "---\ntitle: sample\ncategory: repo\nverified: 2026-09-04\nverified_against: sample @ "+runGitStatusTest(t, repo, "rev-parse", "HEAD")+"\n---\n\n<!-- BEGIN DERIVED: sample -->\nstale\n<!-- END DERIVED -->\n")

	result, err := Derive(root, true)
	if err != nil || result.Status != "would_change" || result.Changed != 1 {
		t.Fatalf("check result = %+v, err=%v", result, err)
	}
	if !strings.Contains(readFileDeriveTest(t, pagePath), "\nstale\n") {
		t.Fatal("check mode changed page")
	}
	result, err = Derive(root, false)
	if err != nil || result.Status != "updated" {
		t.Fatalf("write result = %+v, err=%v", result, err)
	}
	got := readFileDeriveTest(t, pagePath)
	if !strings.Contains(got, "Generated by `wiki/tools/wiki-derive.sh`") || !strings.Contains(got, "| Go version (`go.mod`) | 1.27.1 |") {
		t.Fatalf("page was not derived:\n%s", got)
	}
	result, err = Derive(root, true)
	if err != nil || result.Status != "unchanged" {
		t.Fatalf("second check = %+v, err=%v", result, err)
	}
}

func TestSpliceDerivedPreservesCRLFAndOutsideBytes(t *testing.T) {
	source := []byte("before\r\n<!-- BEGIN DERIVED: sample -->\r\nold\r\n<!-- END DERIVED -->\r\nafter\r\n")
	got, err := spliceDerived(source, "sample", []byte("new\nvalue\n"))
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(got, []byte("before\r\n<!-- BEGIN DERIVED: sample -->\r\nnew\r\nvalue\r\n<!-- END DERIVED -->\r\nafter\r\n")) {
		t.Fatalf("unexpected splice: %q", got)
	}
}

func TestDerivedRepositoryRefusesAmbiguousMarkers(t *testing.T) {
	for name, source := range map[string]string{
		"duplicate start":  "<!-- BEGIN DERIVED: sample -->\n<!-- BEGIN DERIVED: sample -->\n<!-- END DERIVED -->\n",
		"duplicate end":    "<!-- BEGIN DERIVED: sample -->\n<!-- END DERIVED -->\n<!-- END DERIVED -->\n",
		"missing end":      "<!-- BEGIN DERIVED: sample -->\n",
		"end before start": "<!-- END DERIVED -->\n<!-- BEGIN DERIVED: sample -->\n",
	} {
		t.Run(name, func(t *testing.T) {
			repository, marked, err := derivedRepository([]byte(source))
			if err == nil && marked {
				if _, spliceErr := spliceDerived([]byte(source), repository, []byte("generated\n")); spliceErr == nil {
					t.Fatal("ambiguous derived markers were accepted")
				}
			}
		})
	}
}

func readFileDeriveTest(t *testing.T, path string) string {
	t.Helper()
	data, err := readOptionalRegular(path, MaxPageSize)
	if err != nil {
		t.Fatal(err)
	}
	return string(data)
}
