package wiki

import (
	"fmt"
	"regexp"
	"strings"
)

var generatorVersion = regexp.MustCompile(`^v[0-9]+\.[0-9]+\.[0-9]+$`)

// CheckDerivedSelected judges content while reporting generator-only drift.
// DeriveSelected retains its exact-byte preview and write semantics.
func CheckDerivedSelected(root string, selection Selection) (DeriveResult, error) {
	result, err := DeriveSelected(root, true, selection)
	if err != nil {
		return result, err
	}
	for i := range result.Pages {
		page := &result.Pages[i]
		if page.Status != "stale" {
			continue
		}
		old, current, ok := headerVersionOnly(page.Before, page.After, page.Repository)
		if !ok {
			continue
		}
		page.Status = "version_drift"
		page.Reason = fmt.Sprintf("generator version drift: achta %s -> %s; derived content unchanged", old, current)
		result.Changed--
	}
	if result.Changed == 0 {
		result.Status = "unchanged"
	}
	return result, nil
}

func headerVersionOnly(before, after, repository string) (string, string, bool) {
	newline := "\n"
	if strings.Contains(after, "\r\n") {
		newline = "\r\n"
	}
	prefix := "<!-- BEGIN DERIVED: " + repository + " -->" + newline + "Generated by achta "
	start := strings.Index(after, prefix)
	if start < 0 || !strings.HasPrefix(before, after[:start]+prefix) {
		return "", "", false
	}
	start += len(prefix)
	old, tail, found := strings.Cut(before[start:], " ")
	current, freshTail, freshFound := strings.Cut(after[start:], " ")
	if !found || !freshFound || !generatorVersion.MatchString(old) || !generatorVersion.MatchString(current) || old == current || tail != freshTail {
		return "", "", false
	}
	return old, current, true
}
